FROM node:18-alpine AS builder
WORKDIR /app

COPY .env .env
COPY package*.json tsconfig*.json vite.config.ts ./
COPY public ./public
COPY src ./src
COPY index.html ./index.html

RUN npm ci
RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
