FROM node:18-alpine AS build
WORKDIR /app

COPY package*.json tsconfig*.json nest-cli.json ./
COPY prisma ./prisma/
COPY src ./src/
RUN npm ci
RUN npx prisma generate
RUN npm run build

FROM node:18-alpine
WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./

ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "dist/src/main.js"]
